from flask import abort
from math import sqrt
from xml.etree.ElementTree import Element, SubElement, tostring, Comment
from xml.dom.minidom import parseString

def Fibonacci(sequence):
	if (int(sequence) < 0):
		abort(403)
	else:
		return(FibonacciXML(sequence))

def GenerateFibonacciSequence():
	a, b = 0, 1
	while True:
		yield a
		a, b = b, a + b

def FibonacciXML(sequence):
	fibxml = Element("fibonacci")
	fibxml.append(Comment('Fibonacci Sequence - Generated by Mathserver'))

	F = GenerateFibonacciSequence()

	for n in range(int(sequence)):
		value = SubElement(fibxml, "value")
		value.text = str(F.next())
		value.set("index", str(n))
	return(fibxml)

